# Generated by Django 6.0 on 2025-12-19 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cancer_detection', '0004_evidencesource_evidencelink_recommendationevidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfidenceMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('imaging', 'Imaging Analysis'), ('histopathology', 'Histopathology Extraction'), ('genomic', 'Genomic Analysis'), ('treatment_plan', 'Treatment Plan'), ('outcome_prediction', 'Outcome Prediction')], max_length=30)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('data_quality_score', models.FloatField(default=0.0)),
                ('model_certainty_score', models.FloatField(default=0.0)),
                ('evidence_strength_score', models.FloatField(default=0.0)),
                ('confidence_level', models.CharField(choices=[('high', 'High Confidence'), ('moderate', 'Moderate Confidence'), ('low', 'Low Confidence')], default='moderate', max_length=20)),
                ('uncertainty_reasons', models.JSONField(blank=True, default=list)),
                ('missing_data_sources', models.JSONField(blank=True, default=list)),
                ('conflicting_outputs', models.JSONField(blank=True, default=list)),
                ('ocr_quality_score', models.FloatField(blank=True, null=True)),
                ('evidence_breakdown', models.JSONField(blank=True, default=dict)),
                ('detailed_explanation', models.TextField(blank=True, null=True)),
                ('patient_explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_confidence_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Confidence Metadata',
                'verbose_name_plural': 'AI Confidence Metadata',
                'db_table': 'ai_confidence_metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToxicityPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200)),
                ('drug_class', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_toxicities', models.JSONField(default=list)),
                ('high_risk_toxicities', models.JSONField(blank=True, default=list)),
                ('overall_risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='moderate', max_length=20)),
                ('dose_adjustments', models.JSONField(blank=True, default=list)),
                ('correlated_lab_values', models.JSONField(blank=True, default=dict)),
                ('prediction_confidence', models.FloatField(default=0.0)),
                ('patient_summary', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toxicity_predictions', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toxicity_predictions', to='cancer_detection.personalizedtreatmentplan')),
            ],
            options={
                'verbose_name': 'Toxicity Prediction',
                'verbose_name_plural': 'Toxicity Predictions',
                'db_table': 'toxicity_predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TumorBoardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_review', 'In Review'), ('consensus_achieved', 'Consensus Achieved'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('consensus_reached', models.BooleanField(default=False)),
                ('consensus_date', models.DateTimeField(blank=True, null=True)),
                ('final_recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tumor_boards', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumor_board_sessions', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumor_board_sessions', to='cancer_detection.personalizedtreatmentplan')),
            ],
            options={
                'verbose_name': 'Tumor Board Session',
                'verbose_name_plural': 'Tumor Board Sessions',
                'db_table': 'tumor_board_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TumorBoardAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('session_created', 'Session Created'), ('member_invited', 'Member Invited'), ('member_accepted', 'Member Accepted'), ('comment_added', 'Comment Added'), ('decision_made', 'Decision Made'), ('status_changed', 'Status Changed'), ('consensus_reached', 'Consensus Reached'), ('plan_activated', 'Plan Activated')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tumor_board_actions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='clinical_decision_support.tumorboardsession')),
            ],
            options={
                'verbose_name': 'Tumor Board Audit Log',
                'verbose_name_plural': 'Tumor Board Audit Logs',
                'db_table': 'tumor_board_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='XAIExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contributing_factors', models.JSONField(default=list)),
                ('tumor_factors', models.JSONField(blank=True, default=dict)),
                ('genomic_factors', models.JSONField(blank=True, default=dict)),
                ('biomarker_factors', models.JSONField(blank=True, default=dict)),
                ('comorbidity_factors', models.JSONField(blank=True, default=dict)),
                ('recommendation_summary', models.TextField(blank=True, null=True)),
                ('explanation_text', models.TextField(blank=True, null=True)),
                ('structured_explanation', models.JSONField(blank=True, default=dict)),
                ('disclaimer', models.TextField(default='This is clinical decision support only. Final treatment decisions should be made by qualified healthcare professionals in consultation with the patient.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xai_explanations', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xai_explanations', to='cancer_detection.personalizedtreatmentplan')),
            ],
            options={
                'verbose_name': 'XAI Explanation',
                'verbose_name_plural': 'XAI Explanations',
                'db_table': 'xai_explanations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSymptomMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_status', models.CharField(choices=[('none', 'No Alert'), ('attention', 'Needs Attention'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='none', max_length=20)),
                ('latest_symptoms', models.JSONField(blank=True, default=list)),
                ('threshold_breaches', models.JSONField(blank=True, default=list)),
                ('current_treatment_phase', models.CharField(blank=True, max_length=100, null=True)),
                ('phase_correlation', models.JSONField(blank=True, default=dict)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('interventions', models.JSONField(blank=True, default=list)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_patients', to=settings.AUTH_USER_MODEL)),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_symptom_monitors', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_monitors', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_monitors', to='cancer_detection.personalizedtreatmentplan')),
            ],
            options={
                'verbose_name': 'Doctor Symptom Monitor',
                'verbose_name_plural': 'Doctor Symptom Monitors',
                'db_table': 'doctor_symptom_monitors',
                'ordering': ['-updated_at'],
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='TumorBoardMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('medical_oncologist', 'Medical Oncologist'), ('surgical_oncologist', 'Surgical Oncologist'), ('radiation_oncologist', 'Radiation Oncologist'), ('pathologist', 'Pathologist'), ('radiologist', 'Radiologist'), ('geneticist', 'Geneticist'), ('palliative_care', 'Palliative Care Specialist'), ('other', 'Other Specialist')], max_length=30)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suggested_modification', 'Suggested Modification')], default='pending', max_length=25)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('suggested_modifications', models.JSONField(blank=True, default=list)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumor_board_memberships', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clinical_decision_support.tumorboardsession')),
            ],
            options={
                'verbose_name': 'Tumor Board Member',
                'verbose_name_plural': 'Tumor Board Members',
                'db_table': 'tumor_board_members',
                'unique_together': {('session', 'doctor')},
            },
        ),
    ]
