# Generated by Django 6.0 on 2026-01-22 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('brand_names', models.JSONField(blank=True, default=list)),
                ('drug_class', models.CharField(blank=True, max_length=255, null=True)),
                ('therapeutic_class', models.CharField(blank=True, max_length=255, null=True)),
                ('typical_colors', models.JSONField(blank=True, default=list)),
                ('typical_shapes', models.JSONField(blank=True, default=list)),
                ('typical_markings', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('uses', models.JSONField(blank=True, default=list)),
                ('side_effects', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identification_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Medicine Database Entry',
                'verbose_name_plural': 'Medicine Database Entries',
                'ordering': ['medicine_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineIdentification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='medicine_images/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('image_analysis', models.JSONField(blank=True, default=dict)),
                ('medicine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream/Lotion'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('powder', 'Powder'), ('gel', 'Gel'), ('spray', 'Spray'), ('patch', 'Patch'), ('suppository', 'Suppository'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uses', models.JSONField(blank=True, default=list)),
                ('side_effects', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('contraindications', models.JSONField(blank=True, default=list)),
                ('drug_interactions', models.JSONField(blank=True, default=list)),
                ('dosage_instructions', models.TextField(blank=True, null=True)),
                ('storage_instructions', models.TextField(blank=True, null=True)),
                ('active_ingredients', models.JSONField(blank=True, default=list)),
                ('inactive_ingredients', models.JSONField(blank=True, default=list)),
                ('drug_class', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription_required', models.BooleanField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('identification_confidence', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_identifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicine Identification',
                'verbose_name_plural': 'Medicine Identifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
