# Generated by Django 6.0 on 2026-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_identifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineidentification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('invalid_image', 'Invalid Image')], default='pending', max_length=20),
        ),
    ]
