# Generated by Django 6.0 on 2025-12-10 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedTreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cancer_type', models.CharField(max_length=100)),
                ('cancer_stage', models.CharField(max_length=50)),
                ('patient_profile', models.JSONField(default=dict)),
                ('tumor_analysis', models.JSONField(default=dict)),
                ('genetic_profile', models.JSONField(default=dict)),
                ('primary_treatments', models.JSONField(default=list)),
                ('adjuvant_treatments', models.JSONField(default=list)),
                ('targeted_therapies', models.JSONField(default=list)),
                ('side_effects', models.JSONField(default=list)),
                ('predicted_5yr_survival', models.FloatField(blank=True, null=True)),
                ('remission_probability', models.FloatField(blank=True, null=True)),
                ('quality_of_life_score', models.IntegerField(blank=True, null=True)),
                ('monitoring_plan', models.JSONField(default=dict)),
                ('expected_milestones', models.JSONField(default=list)),
                ('treatment_pathway', models.JSONField(default=dict)),
                ('clinical_trials', models.JSONField(default=list)),
                ('contraindications', models.JSONField(default=list)),
                ('special_considerations', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Oncologist Review'), ('approved', 'Approved by Oncologist'), ('active', 'Active/In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('oncologist_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('activated_date', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='cancer_detection.cancerimageanalysis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personalized Treatment Plan',
                'verbose_name_plural': 'Personalized Treatment Plans',
                'db_table': 'personalized_treatment_plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
