# Generated by Django 6.0 on 2025-12-13 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_detection', '0002_personalizedtreatmentplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomicProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutations', models.JSONField(blank=True, default=dict)),
                ('biomarkers', models.JSONField(blank=True, default=dict)),
                ('copy_number_variations', models.JSONField(blank=True, default=dict)),
                ('pd_l1_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pd_l1_percentage', models.FloatField(blank=True, null=True)),
                ('msi_status', models.CharField(blank=True, max_length=50, null=True)),
                ('tumor_mutational_burden', models.FloatField(blank=True, null=True)),
                ('immune_infiltration', models.CharField(blank=True, max_length=50, null=True)),
                ('analysis_results', models.JSONField(blank=True, default=dict)),
                ('actionable_mutations', models.JSONField(blank=True, default=list)),
                ('targeted_therapy_eligibility', models.JSONField(blank=True, default=dict)),
                ('immunotherapy_eligibility', models.JSONField(blank=True, default=dict)),
                ('prognostic_profile', models.JSONField(blank=True, default=dict)),
                ('test_type', models.CharField(blank=True, max_length=100, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomic_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Genomic Profile',
                'verbose_name_plural': 'Genomic Profiles',
                'db_table': 'genomic_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistopathologyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='histopathology_reports/%Y/%m/%d/')),
                ('report_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('analysis_results', models.JSONField(blank=True, default=dict)),
                ('cancer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cancer_subtype', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('tnm_staging', models.CharField(blank=True, max_length=50, null=True)),
                ('tumor_size_mm', models.FloatField(blank=True, null=True)),
                ('margin_status', models.CharField(blank=True, max_length=50, null=True)),
                ('lymph_node_status', models.JSONField(blank=True, default=dict)),
                ('biomarkers', models.JSONField(blank=True, default=dict)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('pathologist_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_lab', models.CharField(blank=True, max_length=200, null=True)),
                ('analysis_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histopathology_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histopathology Report',
                'verbose_name_plural': 'Histopathology Reports',
                'db_table': 'histopathology_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ongoing', 'Treatment Ongoing'), ('completed', 'Treatment Completed'), ('discontinued', 'Treatment Discontinued'), ('follow_up', 'In Follow-up')], default='ongoing', max_length=20)),
                ('treatment_response', models.CharField(blank=True, max_length=50, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('progression_free_survival_days', models.IntegerField(blank=True, null=True)),
                ('overall_survival_days', models.IntegerField(blank=True, null=True)),
                ('quality_of_life_score', models.IntegerField(blank=True, null=True)),
                ('quality_of_life_date', models.DateField(blank=True, null=True)),
                ('side_effects_experienced', models.JSONField(blank=True, default=list)),
                ('side_effects_severity', models.JSONField(blank=True, default=dict)),
                ('predicted_survival', models.FloatField(blank=True, null=True)),
                ('predicted_response', models.FloatField(blank=True, null=True)),
                ('actual_survival', models.FloatField(blank=True, null=True)),
                ('actual_response', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_outcomes', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='cancer_detection.personalizedtreatmentplan')),
            ],
            options={
                'verbose_name': 'Treatment Outcome',
                'verbose_name_plural': 'Treatment Outcomes',
                'db_table': 'treatment_outcomes',
                'ordering': ['-created_at'],
            },
        ),
    ]
