# Generated by Django 6.0 on 2025-12-18 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_detection', '0003_genomicprofile_histopathologyreport_treatmentoutcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('nccn_guideline', 'NCCN Guideline'), ('esmo_guideline', 'ESMO Guideline'), ('asco_guideline', 'ASCO Guideline'), ('pubmed_study', 'PubMed Study'), ('clinical_trial', 'Clinical Trial'), ('case_report', 'Case Report'), ('systematic_review', 'Systematic Review'), ('meta_analysis', 'Meta-Analysis'), ('other', 'Other')], max_length=50)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('journal_or_organization', models.CharField(blank=True, max_length=300, null=True)),
                ('pmid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('guideline_version', models.CharField(blank=True, max_length=100, null=True)),
                ('guideline_url', models.URLField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('key_findings', models.TextField(blank=True, null=True)),
                ('evidence_strength', models.CharField(choices=[('high', 'High - Category 1'), ('moderate', 'Moderate - Category 2A/2B'), ('low', 'Low - Category 3')], default='moderate', max_length=20)),
                ('cancer_types', models.JSONField(blank=True, default=list)),
                ('treatment_types', models.JSONField(blank=True, default=list)),
                ('biomarkers', models.JSONField(blank=True, default=list)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_indexed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evidence Source',
                'verbose_name_plural': 'Evidence Sources',
                'db_table': 'evidence_sources',
                'ordering': ['-publication_year', '-created_at'],
                'indexes': [models.Index(fields=['pmid'], name='evidence_so_pmid_5d727f_idx'), models.Index(fields=['source_type'], name='evidence_so_source__120bb7_idx'), models.Index(fields=['evidence_strength'], name='evidence_so_evidenc_1f9551_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance_type', models.CharField(choices=[('directly_supports', 'Directly Supports'), ('partially_supports', 'Partially Supports'), ('comparative_evidence', 'Comparative Evidence'), ('contraindication', 'Contraindication'), ('related_finding', 'Related Finding')], default='directly_supports', max_length=50)),
                ('relevance_score', models.FloatField(default=0.8)),
                ('how_evidence_supports', models.TextField(blank=True, null=True)),
                ('relevant_excerpts', models.JSONField(blank=True, default=list)),
                ('impact_percentage', models.FloatField(default=0.0)),
                ('evidence_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer_detection.evidencesource')),
            ],
            options={
                'verbose_name': 'Evidence Link',
                'verbose_name_plural': 'Evidence Links',
                'db_table': 'evidence_links',
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(max_length=200)),
                ('recommendation_text', models.TextField()),
                ('total_evidence_score', models.FloatField(default=0.0)),
                ('high_strength_count', models.IntegerField(default=0)),
                ('moderate_strength_count', models.IntegerField(default=0)),
                ('low_strength_count', models.IntegerField(default=0)),
                ('decision_factors', models.JSONField(default=dict)),
                ('recommendation_confidence', models.FloatField(default=0.0)),
                ('alternative_recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_sources', models.ManyToManyField(through='cancer_detection.EvidenceLink', to='cancer_detection.evidencesource')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_evidences', to='cancer_detection.personalizedtreatmentplan')),
            ],
            options={
                'verbose_name': 'Recommendation Evidence',
                'verbose_name_plural': 'Recommendation Evidences',
                'db_table': 'recommendation_evidences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='evidencelink',
            name='recommendation_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer_detection.recommendationevidence'),
        ),
        migrations.CreateModel(
            name='EvidenceExplanationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('explanation_type', models.CharField(max_length=50)),
                ('explanation_returned', models.JSONField(default=dict)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer_detection.personalizedtreatmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_explanations', to=settings.AUTH_USER_MODEL)),
                ('sources_shown', models.ManyToManyField(to='cancer_detection.evidencesource')),
                ('recommendation_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cancer_detection.recommendationevidence')),
            ],
            options={
                'verbose_name': 'Evidence Explanation Log',
                'verbose_name_plural': 'Evidence Explanation Logs',
                'db_table': 'evidence_explanation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleBasedReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('cancer_type', models.CharField(max_length=100)),
                ('cancer_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('biomarker_requirement', models.JSONField(blank=True, default=dict)),
                ('recommended_treatment', models.CharField(max_length=200)),
                ('guideline_references', models.JSONField(default=list)),
                ('pubmed_references', models.JSONField(default=list)),
                ('evidence_strength', models.CharField(choices=[('high', 'High - Category 1'), ('moderate', 'Moderate - Category 2A/2B'), ('low', 'Low - Category 3')], default='moderate', max_length=20)),
                ('rule_logic', models.TextField()),
                ('priority_level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rule-Based Reference',
                'verbose_name_plural': 'Rule-Based References',
                'db_table': 'rule_based_references',
                'ordering': ['-priority_level', 'cancer_type'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='evidencelink',
            unique_together={('recommendation_evidence', 'evidence_source')},
        ),
    ]
