# Generated by Django 6.0 on 2025-12-19 08:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cancer_detection', '0004_evidencesource_evidencelink_recommendationevidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_in_app', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('enable_whatsapp', models.BooleanField(default=False)),
                ('enable_email', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('symptom_reminder_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('none', 'No Reminders')], default='daily', max_length=20)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Notification Preference',
                'verbose_name_plural': 'Patient Notification Preferences',
                'db_table': 'patient_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='PatientSideEffectInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treatment_name', models.CharField(max_length=200)),
                ('common_side_effects', models.JSONField(default=list)),
                ('what_is_normal', models.JSONField(blank=True, default=list)),
                ('when_to_contact_doctor', models.JSONField(blank=True, default=list)),
                ('self_care_tips', models.JSONField(blank=True, default=list)),
                ('emergency_signs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_info', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_side_effects', to='cancer_detection.personalizedtreatmentplan')),
            ],
            options={
                'verbose_name': 'Patient Side Effect Info',
                'verbose_name_plural': 'Patient Side Effect Info',
                'db_table': 'patient_side_effect_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientSymptomLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField(default=django.utils.timezone.now)),
                ('log_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('fatigue', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('pain', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('pain_location', models.CharField(blank=True, max_length=200, null=True)),
                ('nausea', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('vomiting', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('appetite_loss', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('weight_change', models.CharField(blank=True, max_length=50, null=True)),
                ('sleep_problems', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('shortness_of_breath', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('diarrhea', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('constipation', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('mouth_sores', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('skin_changes', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('numbness_tingling', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('fever', models.BooleanField(default=False)),
                ('fever_temperature', models.FloatField(blank=True, null=True)),
                ('anxiety', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('depression', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('confusion', models.IntegerField(blank=True, choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Very Severe')], null=True)),
                ('hair_loss', models.CharField(blank=True, choices=[('none', 'None'), ('minimal', 'Minimal'), ('moderate', 'Moderate'), ('significant', 'Significant'), ('complete', 'Complete')], max_length=50, null=True)),
                ('overall_wellbeing', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Very Good')], null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('bedridden', 'Bedridden'), ('mostly_rest', 'Mostly Resting'), ('limited', 'Limited Activity'), ('normal', 'Normal Activity')], max_length=50, null=True)),
                ('additional_symptoms', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_submitted', models.BooleanField(default=True)),
                ('reviewed_by_doctor', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_response', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_symptom_logs', to='cancer_detection.personalizedtreatmentplan')),
            ],
            options={
                'verbose_name': 'Patient Symptom Log',
                'verbose_name_plural': 'Patient Symptom Logs',
                'db_table': 'patient_symptom_logs',
                'ordering': ['-log_date', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('symptom_reminder', 'Symptom Log Reminder'), ('doctor_review', 'Doctor Reviewed Symptoms'), ('appointment', 'Appointment Reminder'), ('medication', 'Medication Reminder'), ('reassurance', 'Reassurance Message'), ('general', 'General Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('in_app', 'In-App Notification'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='in_app', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('related_symptom_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='patient_portal.patientsymptomlog')),
            ],
            options={
                'verbose_name': 'Patient Alert',
                'verbose_name_plural': 'Patient Alerts',
                'db_table': 'patient_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientTreatmentExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treatment_summary', models.TextField()),
                ('why_this_treatment', models.TextField(blank=True, null=True)),
                ('expected_benefits', models.JSONField(default=list)),
                ('treatment_steps', models.JSONField(default=list)),
                ('estimated_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('key_milestones', models.JSONField(blank=True, default=list)),
                ('what_to_expect', models.JSONField(blank=True, default=list)),
                ('suggested_questions', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_explanations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_explanations', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_explanation', to='cancer_detection.personalizedtreatmentplan')),
            ],
            options={
                'verbose_name': 'Patient Treatment Explanation',
                'verbose_name_plural': 'Patient Treatment Explanations',
                'db_table': 'patient_treatment_explanations',
                'ordering': ['-created_at'],
            },
        ),
    ]
