# Generated by Django 6.0 on 2026-01-22 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_portal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("symptom_tracking", "Symptom Tracking"),
                            ("consistency", "Consistency"),
                            ("wellness", "Wellness"),
                            ("milestone", "Milestone"),
                            ("social", "Social"),
                            ("treatment", "Treatment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("icon_url", models.URLField(blank=True, max_length=500, null=True)),
                ("icon_name", models.CharField(blank=True, max_length=100, null=True)),
                ("points_reward", models.IntegerField(default=0)),
                ("criteria", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "db_table": "gamification_badges",
                "ordering": ["category", "rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="HealthChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("symptom_logging", "Symptom Logging"),
                            ("wellness", "Wellness"),
                            ("consistency", "Consistency"),
                            ("social", "Social"),
                            ("treatment", "Treatment"),
                            ("custom", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                ("goal_description", models.TextField()),
                ("goal_value", models.IntegerField(default=1)),
                ("goal_unit", models.CharField(default="times", max_length=50)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("duration_days", models.IntegerField(blank=True, null=True)),
                ("points_reward", models.IntegerField(default=0)),
                ("custom_reward", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                ("min_level_required", models.IntegerField(default=1)),
                ("criteria", models.JSONField(default=dict)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "badge_reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="patient_portal.badge",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Challenge",
                "verbose_name_plural": "Health Challenges",
                "db_table": "gamification_health_challenges",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("points", "Points"),
                            ("badge", "Badge"),
                            ("discount", "Discount"),
                            ("virtual", "Virtual Item"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points_value", models.IntegerField(blank=True, null=True)),
                (
                    "discount_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("discount_percentage", models.FloatField(blank=True, null=True)),
                ("custom_value", models.TextField(blank=True, null=True)),
                ("points_required", models.IntegerField(default=0)),
                ("level_required", models.IntegerField(default=1)),
                ("is_available", models.BooleanField(default=True)),
                ("max_claims", models.IntegerField(blank=True, null=True)),
                ("current_claims", models.IntegerField(default=0)),
                ("max_claims_per_user", models.IntegerField(default=1)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "badge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewards",
                        to="patient_portal.badge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
                "db_table": "gamification_rewards",
                "ordering": ["points_required", "name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityFeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("badge_earned", "Badge Earned"),
                            ("challenge_completed", "Challenge Completed"),
                            ("level_up", "Level Up"),
                            ("streak_milestone", "Streak Milestone"),
                            ("reward_claimed", "Reward Claimed"),
                            ("friend_added", "Friend Added"),
                            ("custom", "Custom Activity"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("points_earned", models.IntegerField(default=0)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_feed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_badge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_feeds",
                        to="patient_portal.badge",
                    ),
                ),
                (
                    "related_challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_feeds",
                        to="patient_portal.healthchallenge",
                    ),
                ),
                (
                    "related_reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_feeds",
                        to="patient_portal.reward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Feed",
                "verbose_name_plural": "Activity Feed",
                "db_table": "gamification_activity_feed",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("lifetime_points", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("experience_points", models.IntegerField(default=0)),
                ("points_to_next_level", models.IntegerField(default=100)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("total_symptom_logs", models.IntegerField(default=0)),
                ("total_challenges_completed", models.IntegerField(default=0)),
                ("total_badges_earned", models.IntegerField(default=0)),
                ("weekly_points", models.IntegerField(default=0)),
                ("monthly_points", models.IntegerField(default=0)),
                ("weekly_reset_date", models.DateField(blank=True, null=True)),
                ("monthly_reset_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamification_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "User Progress",
                "db_table": "gamification_user_progress",
            },
        ),
        migrations.CreateModel(
            name="UserReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                ("points_spent", models.IntegerField(default=0)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("claim_code", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_rewards",
                        to="patient_portal.reward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claimed_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Reward",
                "verbose_name_plural": "User Rewards",
                "db_table": "gamification_user_rewards",
                "ordering": ["-claimed_at"],
            },
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Friend Request",
                "verbose_name_plural": "Friend Requests",
                "db_table": "gamification_friend_requests",
                "ordering": ["-created_at"],
                "unique_together": {("from_user", "to_user")},
            },
        ),
        migrations.CreateModel(
            name="ChallengeParticipation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("joined", "Joined"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="joined",
                        max_length=20,
                    ),
                ),
                ("progress_value", models.IntegerField(default=0)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reward_claimed", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="patient_portal.healthchallenge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge Participation",
                "verbose_name_plural": "Challenge Participations",
                "db_table": "gamification_challenge_participations",
                "ordering": ["-joined_at"],
                "unique_together": {("user", "challenge")},
            },
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField(blank=True, null=True)),
                ("rank", models.IntegerField()),
                ("points", models.IntegerField(default=0)),
                ("challenges_completed", models.IntegerField(default=0)),
                ("badges_earned", models.IntegerField(default=0)),
                ("streak_days", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leaderboard Entry",
                "verbose_name_plural": "Leaderboard Entries",
                "db_table": "gamification_leaderboard_entries",
                "ordering": ["period", "rank", "-points"],
                "unique_together": {("user", "period", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_activity_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_activity_id", models.UUIDField(blank=True, null=True)),
                ("notification_sent", models.BooleanField(default=False)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="patient_portal.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "db_table": "gamification_user_badges",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
        migrations.CreateModel(
            name="UserFriend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_of",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Friend",
                "verbose_name_plural": "User Friends",
                "db_table": "gamification_user_friends",
                "ordering": ["-created_at"],
                "unique_together": {("user", "friend")},
            },
        ),
    ]
