# Generated by Django 6.0 on 2026-01-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0003_consultation_call_initiated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='doctor_answer',
            field=models.TextField(blank=True, help_text='WebRTC answer from doctor'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_ice_candidates',
            field=models.TextField(blank=True, help_text='ICE candidates from doctor (JSON)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_ice_candidates',
            field=models.TextField(blank=True, help_text='ICE candidates from patient (JSON)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_offer',
            field=models.TextField(blank=True, help_text='WebRTC offer from patient'),
        ),
    ]
