# Generated by Django 6.0 on 2026-01-22 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0004_consultation_doctor_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.TextField(help_text='Patient diagnosis')),
                ('symptoms', models.TextField(blank=True, help_text='Observed symptoms')),
                ('doctor_notes', models.TextField(blank=True, help_text='Additional instructions or notes')),
                ('follow_up_instructions', models.TextField(blank=True, help_text='Follow-up care instructions')),
                ('pdf_hash', models.CharField(blank=True, help_text='SHA-256 hash of PDF', max_length=64)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='prescription_qr/')),
                ('verification_url', models.URLField(blank=True, help_text='URL for prescription verification')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Blockchain verification status')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_detail', to='patient_portal.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_issued', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(help_text='Generic or Brand name', max_length=255)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 10ml, 1 tablet', max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily (Morning & Evening)'), ('thrice_daily', 'Thrice Daily (Morning, Afternoon & Evening)'), ('four_times', 'Four Times Daily'), ('every_4_hours', 'Every 4 Hours'), ('every_6_hours', 'Every 6 Hours'), ('every_8_hours', 'Every 8 Hours'), ('every_12_hours', 'Every 12 Hours'), ('as_needed', 'As Needed'), ('before_meals', 'Before Meals'), ('after_meals', 'After Meals'), ('at_bedtime', 'At Bedtime')], max_length=50)),
                ('timing', models.CharField(choices=[('before_food', 'Before Food'), ('after_food', 'After Food'), ('with_food', 'With Food'), ('empty_stomach', 'Empty Stomach'), ('anytime', 'Anytime')], default='after_food', max_length=50)),
                ('duration_days', models.IntegerField(help_text='Duration in days')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for this medicine')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='patient_portal.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Medicine',
                'verbose_name_plural': 'Prescription Medicines',
                'db_table': 'prescription_medicines',
                'ordering': ['order', 'medicine_name'],
            },
        ),
    ]
