# Generated by Django 6.0 on 2026-01-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0002_badge_healthchallenge_reward_activityfeed_and_more'),
        ('patient_portal', '0006_allow_multiple_prescriptions'),
    ]

    operations = [
    ]
