# Generated by Django 6.0 on 2026-01-21 13:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('authentication', '0001_initial'), ('authentication', '0002_doctorprofile_additional_qualifications_and_more'), ('authentication', '0003_alter_doctorprofile_specialization_medicalrecord'), ('authentication', '0002_doctor_kyc'), ('authentication', '0004_merge_20251206_1231'), ('authentication', '0005_alter_medicalrecord_options_and_more'), ('authentication', '0006_delete_old_qr_tables'), ('authentication', '0007_patientqrcode_qrcodescanlog'), ('authentication', '0008_rename_qrcodescanlog_table'), ('authentication', '0009_rename_medicalrecord_fields'), ('authentication', '0010_refactor_doctorkyc_schema'), ('authentication', '0011_fix_verified_by_column'), ('authentication', '0012_alter_doctorkyc_options_alter_patientqrcode_options_and_more'), ('authentication', '0013_sync_database_schema')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], max_length=10)),
                ('supabase_user_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('profile_picture', models.URLField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('hospital_affiliation', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_profiles',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_profiles',
            },
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='additional_qualifications',
            field=models.TextField(blank=True, help_text='Other certifications or qualifications', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Comma-separated languages', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_degree',
            field=models.CharField(blank=True, help_text='e.g., MBBS, MD, DM', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief description about yourself and expertise', null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('oncology', 'Oncology'), ('surgical_oncology', 'Surgical Oncology'), ('radiation_oncology', 'Radiation Oncology'), ('medical_oncology', 'Medical Oncology'), ('pediatric_oncology', 'Pediatric Oncology'), ('hematology', 'Hematology'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general_medicine', 'General Medicine'), ('internal_medicine', 'Internal Medicine'), ('family_medicine', 'Family Medicine'), ('pediatrics', 'Pediatrics'), ('surgery', 'General Surgery'), ('orthopedics', 'Orthopedics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('psychiatry', 'Psychiatry'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('gynecology', 'Gynecology & Obstetrics'), ('urology', 'Urology'), ('nephrology', 'Nephrology'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology'), ('endocrinology', 'Endocrinology'), ('rheumatology', 'Rheumatology'), ('oncology', 'Oncology'), ('surgical_oncology', 'Surgical Oncology'), ('radiation_oncology', 'Radiation Oncology'), ('medical_oncology', 'Medical Oncology'), ('pediatric_oncology', 'Pediatric Oncology'), ('hematology', 'Hematology'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('critical_care', 'Critical Care Medicine'), ('plastic_surgery', 'Plastic Surgery'), ('neurosurgery', 'Neurosurgery'), ('cardiothoracic_surgery', 'Cardiothoracic Surgery'), ('vascular_surgery', 'Vascular Surgery'), ('transplant_surgery', 'Transplant Surgery'), ('infectious_disease', 'Infectious Disease'), ('allergy_immunology', 'Allergy & Immunology'), ('geriatrics', 'Geriatrics'), ('sports_medicine', 'Sports Medicine'), ('physical_medicine', 'Physical Medicine & Rehabilitation'), ('occupational_medicine', 'Occupational Medicine'), ('preventive_medicine', 'Preventive Medicine'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('radiology', 'Radiology Report'), ('pathology', 'Pathology Report'), ('biopsy', 'Biopsy Report'), ('blood_test', 'Blood Test'), ('genetic_test', 'Genetic Test'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('consultation', 'Consultation Notes'), ('other', 'Other')], default='other', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='medical_records/%Y/%m/%d/')),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('ocr_status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('personal_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('residential_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('license_number_verified', models.CharField(max_length=100)),
                ('license_issuing_authority', models.CharField(max_length=200)),
                ('license_issue_date', models.DateField()),
                ('license_expiry_date', models.DateField()),
                ('license_document', models.FileField(blank=True, null=True, upload_to='kyc/licenses/')),
                ('medical_degree', models.CharField(max_length=200)),
                ('medical_university', models.CharField(max_length=200)),
                ('graduation_year', models.IntegerField()),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to='kyc/degrees/')),
                ('current_hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('department_specialty', models.CharField(max_length=100)),
                ('years_of_practice', models.IntegerField()),
                ('employment_document', models.FileField(blank=True, null=True, upload_to='kyc/employment/')),
                ('identity_document_type', models.CharField(choices=[('passport', 'Passport'), ('aadhaar', 'Aadhaar'), ('national_id', 'National ID'), ('driving_license', 'Driving License')], max_length=50)),
                ('identity_document_number', models.CharField(max_length=100)),
                ('identity_document_file', models.FileField(blank=True, null=True, upload_to='kyc/identity/')),
                ('address_proof_type', models.CharField(choices=[('utility_bill', 'Utility Bill'), ('rental_agreement', 'Rental Agreement'), ('property_deed', 'Property Deed'), ('bank_statement', 'Bank Statement')], max_length=50)),
                ('address_proof_file', models.FileField(blank=True, null=True, upload_to='kyc/address_proof/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='authentication.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor KYC',
                'verbose_name_plural': 'Doctor KYCs',
                'db_table': 'doctor_kyc',
            },
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medical Record', 'verbose_name_plural': 'Medical Records'},
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('lab_report', 'Laboratory Report'), ('radiology', 'Radiology Report'), ('pathology', 'Pathology Report'), ('biopsy', 'Biopsy Report'), ('blood_test', 'Blood Test'), ('genetic_test', 'Genetic Test'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('consultation', 'Consultation Notes'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS authentication_patientqrcode CASCADE;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS authentication_qrcodescanlog CASCADE;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS patient_qr_codes CASCADE;',
            reverse_sql='',
        ),
        migrations.CreateModel(
            name='PatientQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='patient_qr_codes/')),
                ('qr_code_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regenerated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('last_scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_patient_qr_codes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient QR Code',
                'verbose_name_plural': 'Patient QR Codes',
                'ordering': ['-created_at'],
                'db_table': 'patient_qr_codes',
            },
        ),
        migrations.CreateModel(
            name='QRCodeScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('access_granted', models.BooleanField(default=True)),
                ('denial_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scan_logs_as_patient', to=settings.AUTH_USER_MODEL)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='authentication.patientqrcode')),
                ('scanned_by', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Code Scan Log',
                'verbose_name_plural': 'QR Code Scan Logs',
                'ordering': ['-scan_timestamp'],
            },
        ),
        migrations.RunSQL(
            sql='ALTER TABLE authentication_qrcodescanlog RENAME TO qr_code_scan_logs;',
            reverse_sql='ALTER TABLE qr_code_scan_logs RENAME TO authentication_qrcodescanlog;',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='record_type',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='file',
            new_name='document_file',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='state',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='country',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='license_number_verified',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='license_issuing_authority',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='license_issue_date',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='license_expiry_date',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='license_document',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='medical_degree',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='medical_university',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='degree_certificate',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='current_hospital',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='department_specialty',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='years_of_practice',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='employment_document',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='identity_document_type',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='identity_document_number',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='identity_document_file',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='address_proof_file',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='id_type',
            field=models.CharField(choices=[('aadhar', 'Aadhar'), ('pan', 'PAN'), ('passport', 'Passport')], default='pan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='id_document',
            field=models.FileField(default='', upload_to='doctor_kyc/id_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='registration_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='registration_council',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='registration_document',
            field=models.FileField(default='', upload_to='doctor_kyc/registration_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='degree_document',
            field=models.FileField(default='', upload_to='doctor_kyc/degree_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='address_proof_document',
            field=models.FileField(default='', upload_to='doctor_kyc/address_proofs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='verified_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE doctor_kyc RENAME COLUMN verified_by_id_id TO verified_by_id;',
            reverse_sql='ALTER TABLE doctor_kyc RENAME COLUMN verified_by_id TO verified_by_id_id;',
        ),
        migrations.AlterModelOptions(
            name='doctorkyc',
            options={'verbose_name': 'Doctor KYC', 'verbose_name_plural': 'Doctor KYC'},
        ),
        migrations.AlterModelOptions(
            name='patientqrcode',
            options={'verbose_name': 'Patient QR Code', 'verbose_name_plural': 'Patient QR Codes'},
        ),
        migrations.RunSQL(
            sql='ALTER TABLE doctor_kyc DROP COLUMN IF EXISTS verified_by_id;',
            reverse_sql='ALTER TABLE doctor_kyc ADD COLUMN verified_by_id uuid NULL;',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='file_size',
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorkyc',
            name='address_proof_type',
            field=models.CharField(choices=[('electricity_bill', 'Electricity Bill'), ('gas_bill', 'Gas Bill'), ('water_bill', 'Water Bill')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorkyc',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctorkyc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='document_type',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('imaging_report', 'Imaging Report'), ('discharge_summary', 'Discharge Summary'), ('medical_history', 'Medical History'), ('vaccination_record', 'Vaccination Record'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Pending OCR'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientqrcode',
            name='regenerated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodescanlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='qrcodescanlog',
            table='qr_code_scan_logs',
        ),
        migrations.RemoveField(
            model_name='doctorkyc',
            name='verified_by_id',
        ),
    ]
