# Generated by Django 6.0 on 2025-12-05 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_doctorprofile_additional_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general_medicine', 'General Medicine'), ('internal_medicine', 'Internal Medicine'), ('family_medicine', 'Family Medicine'), ('pediatrics', 'Pediatrics'), ('surgery', 'General Surgery'), ('orthopedics', 'Orthopedics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('psychiatry', 'Psychiatry'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('gynecology', 'Gynecology & Obstetrics'), ('urology', 'Urology'), ('nephrology', 'Nephrology'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology'), ('endocrinology', 'Endocrinology'), ('rheumatology', 'Rheumatology'), ('oncology', 'Oncology'), ('surgical_oncology', 'Surgical Oncology'), ('radiation_oncology', 'Radiation Oncology'), ('medical_oncology', 'Medical Oncology'), ('pediatric_oncology', 'Pediatric Oncology'), ('hematology', 'Hematology'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('critical_care', 'Critical Care Medicine'), ('plastic_surgery', 'Plastic Surgery'), ('neurosurgery', 'Neurosurgery'), ('cardiothoracic_surgery', 'Cardiothoracic Surgery'), ('vascular_surgery', 'Vascular Surgery'), ('transplant_surgery', 'Transplant Surgery'), ('infectious_disease', 'Infectious Disease'), ('allergy_immunology', 'Allergy & Immunology'), ('geriatrics', 'Geriatrics'), ('sports_medicine', 'Sports Medicine'), ('physical_medicine', 'Physical Medicine & Rehabilitation'), ('occupational_medicine', 'Occupational Medicine'), ('preventive_medicine', 'Preventive Medicine'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('radiology', 'Radiology Report'), ('pathology', 'Pathology Report'), ('biopsy', 'Biopsy Report'), ('blood_test', 'Blood Test'), ('genetic_test', 'Genetic Test'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('consultation', 'Consultation Notes'), ('other', 'Other')], default='other', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='medical_records/%Y/%m/%d/')),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('ocr_status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
