# Generated by Django 6.0 on 2025-12-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_doctor_kyc'),
        ('authentication', '0003_alter_doctorprofile_specialization_medicalrecord'),
    ]

    operations = [
    ]
