# Generated by Django 6.0 on 2025-12-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merge_20251206_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medical Record', 'verbose_name_plural': 'Medical Records'},
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('lab_report', 'Laboratory Report'), ('radiology', 'Radiology Report'), ('pathology', 'Pathology Report'), ('biopsy', 'Biopsy Report'), ('blood_test', 'Blood Test'), ('genetic_test', 'Genetic Test'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('consultation', 'Consultation Notes'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
