# Generated by Django 6.0 on 2025-12-13 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_fix_verified_by_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorkyc',
            options={'verbose_name': 'Doctor KYC', 'verbose_name_plural': 'Doctor KYC'},
        ),
        migrations.AlterModelOptions(
            name='patientqrcode',
            options={'verbose_name': 'Patient QR Code', 'verbose_name_plural': 'Patient QR Codes'},
        ),
        # Use RunSQL to drop the column directly since the Django field name doesn't match DB column
        migrations.RunSQL(
            sql="ALTER TABLE doctor_kyc DROP COLUMN IF EXISTS verified_by_id;",
            reverse_sql="ALTER TABLE doctor_kyc ADD COLUMN verified_by_id uuid NULL;",
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='file_size',
        ),
        migrations.AddField(
            model_name='doctorkyc',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorkyc',
            name='address_proof_type',
            field=models.CharField(choices=[('electricity_bill', 'Electricity Bill'), ('gas_bill', 'Gas Bill'), ('water_bill', 'Water Bill')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorkyc',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctorkyc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='document_type',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('imaging_report', 'Imaging Report'), ('discharge_summary', 'Discharge Summary'), ('medical_history', 'Medical History'), ('vaccination_record', 'Vaccination Record'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Pending OCR'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientqrcode',
            name='regenerated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodescanlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='qrcodescanlog',
            table='qr_code_scan_logs',
        ),
    ]
