# Generated by Django 6.0 on 2025-12-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_doctorkyc_options_alter_patientqrcode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorkyc',
            name='verified_by_id',
        ),
    ]
