# Generated by Django 6.0 on 2026-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_add_blockchain_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorkyc",
            name="clinic_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorkyc",
            name="clinic_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorkyc",
            name="clinic_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
