# Generated by Django 6.0 on 2026-01-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_doctorkyc_clinic_address_doctorkyc_clinic_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_phone',
            field=models.CharField(blank=True, help_text='Hospital contact number', max_length=20, null=True),
        ),
    ]
