# Generated by Django 6.0 on 2026-01-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_add_blockchain_fields'),
        ('authentication', '0015_fix_id_column_type'),
    ]

    operations = [
    ]
