# Generated by Django 6.0 on 2026-01-22 06:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scheme_type', models.CharField(choices=[('health', 'Health Insurance'), ('life', 'Life Insurance'), ('accident', 'Accident Cover'), ('pension', 'Pension Scheme'), ('education', 'Education Support'), ('agriculture', 'Agriculture Support')], max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('coverage_amount', models.DecimalField(decimal_places=2, help_text='Maximum coverage in INR', max_digits=12)),
                ('benefits', models.TextField(help_text='List of key benefits')),
                ('required_documents', models.TextField(help_text='Documents needed for application')),
                ('application_steps', models.TextField(help_text='Steps to apply')),
                ('official_website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Scheme',
                'verbose_name_plural': 'Government Schemes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(choices=[('health', 'Health Insurance'), ('life', 'Life Insurance'), ('accident', 'Accident Cover'), ('family', 'Family Plan'), ('senior', 'Senior Citizen Plan')], max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('premium_per_month', models.DecimalField(decimal_places=2, help_text='Starting premium in INR', max_digits=10)),
                ('coverage_amount', models.DecimalField(decimal_places=2, help_text='Maximum coverage in INR', max_digits=12)),
                ('key_features', models.TextField(help_text='Key features of the policy')),
                ('cashless_hospitals', models.BooleanField(default=True)),
                ('claim_support', models.BooleanField(default=True)),
                ('add_ons_available', models.TextField(blank=True, null=True)),
                ('min_age', models.IntegerField(default=18)),
                ('max_age', models.IntegerField(default=65)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance Policy',
                'verbose_name_plural': 'Insurance Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_age', models.IntegerField(help_text='Minimum age requirement')),
                ('max_age', models.IntegerField(help_text='Maximum age requirement')),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum annual income in INR', max_digits=12, null=True)),
                ('state', models.CharField(blank=True, help_text='Specific state requirement', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, help_text='Gender requirement if any', max_length=20, null=True)),
                ('additional_criteria', models.TextField(blank=True, null=True)),
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='Insurance_SIP.governmentscheme')),
            ],
            options={
                'verbose_name': 'Eligibility Criteria',
                'verbose_name_plural': 'Eligibility Criteria',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('documents_required', 'Documents Required')], default='draft', max_length=30)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_age', models.IntegerField()),
                ('applicant_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applicant_state', models.CharField(max_length=100)),
                ('documents_uploaded', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_applications', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='Insurance_SIP.governmentscheme')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='Insurance_SIP.insurancepolicy')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
